package com.grt.filemanager.orm.dao.base;

import android.database.sqlite.SQLiteDatabase;

import com.grt.filemanager.orm.dao.App;
import com.grt.filemanager.orm.dao.AppFolder;
import com.grt.filemanager.orm.dao.BoxAccount;
import com.grt.filemanager.orm.dao.BoxFile;
import com.grt.filemanager.orm.dao.DownloadMusic;
import com.grt.filemanager.orm.dao.DownloadedFile;
import com.grt.filemanager.orm.dao.DropboxAccount;
import com.grt.filemanager.orm.dao.DropboxFile;
import com.grt.filemanager.orm.dao.FavourateMusic;
import com.grt.filemanager.orm.dao.FePrivateCloudAccount;
import com.grt.filemanager.orm.dao.FePrivateCloudFile;
import com.grt.filemanager.orm.dao.FeSmbFile;
import com.grt.filemanager.orm.dao.FragmentInfo;
import com.grt.filemanager.orm.dao.FtpAccount;
import com.grt.filemanager.orm.dao.FtpFileInfo;
import com.grt.filemanager.orm.dao.GCloudAccount;
import com.grt.filemanager.orm.dao.GCloudFile;
import com.grt.filemanager.orm.dao.GoogleDriveAccount;
import com.grt.filemanager.orm.dao.GoogleDriveFile;
import com.grt.filemanager.orm.dao.Label;
import com.grt.filemanager.orm.dao.LabelFile;
import com.grt.filemanager.orm.dao.MixCloudAccount;
import com.grt.filemanager.orm.dao.MixCloudFile;
import com.grt.filemanager.orm.dao.OneDriveAccount;
import com.grt.filemanager.orm.dao.OneDriveFile;
import com.grt.filemanager.orm.dao.Partition;
import com.grt.filemanager.orm.dao.RecentMusic;
import com.grt.filemanager.orm.dao.RecentOpen;
import com.grt.filemanager.orm.dao.Search;
import com.grt.filemanager.orm.dao.SinaStorageAccount;
import com.grt.filemanager.orm.dao.SinaStorageFile;
import com.grt.filemanager.orm.dao.SmbAccount;
import com.grt.filemanager.orm.dao.Statistics;
import com.grt.filemanager.orm.dao.Storage;
import com.grt.filemanager.orm.dao.SugarsyncAccount;
import com.grt.filemanager.orm.dao.SugarsyncFile;
import com.grt.filemanager.orm.dao.SyncHistory;
import com.grt.filemanager.orm.dao.SyncInfo;
import com.grt.filemanager.orm.dao.SyncSetting;
import com.grt.filemanager.orm.dao.WebDavAccount;
import com.grt.filemanager.orm.dao.WebDavFile;
import com.grt.filemanager.orm.dao.YandexAccount;
import com.grt.filemanager.orm.dao.YandexFile;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig fragmentInfoDaoConfig;
    private final DaoConfig storageDaoConfig;
    private final DaoConfig statisticsDaoConfig;
    private final DaoConfig appDaoConfig;
    private final DaoConfig searchDaoConfig;
    private final DaoConfig recentOpenDaoConfig;
    private final DaoConfig labelDaoConfig;
    private final DaoConfig labelFileDaoConfig;
    private final DaoConfig downloadedFileDaoConfig;
    private final DaoConfig favourateMusicDaoConfig;
    private final DaoConfig recentMusicDaoConfig;
    private final DaoConfig downloadMusicDaoConfig;
    private final DaoConfig dropboxAccountDaoConfig;
    private final DaoConfig webDavAccountDaoConfig;
    private final DaoConfig fePrivateCloudAccountDaoConfig;
    private final DaoConfig sinaStorageAccountDaoConfig;
    private final DaoConfig dropboxFileDaoConfig;
    private final DaoConfig webDavFileDaoConfig;
    private final DaoConfig fePrivateCloudFileDaoConfig;
    private final DaoConfig sinaStorageFileDaoConfig;
    private final DaoConfig googleDriveAccountDaoConfig;
    private final DaoConfig oneDriveAccountDaoConfig;
    private final DaoConfig boxAccountDaoConfig;
    private final DaoConfig yandexAccountDaoConfig;
    private final DaoConfig sugarsyncAccountDaoConfig;
    private final DaoConfig mixCloudAccountDaoConfig;
    private final DaoConfig googleDriveFileDaoConfig;
    private final DaoConfig oneDriveFileDaoConfig;
    private final DaoConfig boxFileDaoConfig;
    private final DaoConfig yandexFileDaoConfig;
    private final DaoConfig sugarsyncFileDaoConfig;
    private final DaoConfig mixCloudFileDaoConfig;
    private final DaoConfig appFolderDaoConfig;
    private final DaoConfig ftpFileInfoDaoConfig;
    private final DaoConfig ftpAccountDaoConfig;
    private final DaoConfig feSmbFileDaoConfig;
    private final DaoConfig smbAccountDaoConfig;
    private final DaoConfig gCloudAccountDaoConfig;
    private final DaoConfig gCloudFileDaoConfig;
    private final DaoConfig syncInfoDaoConfig;
    private final DaoConfig syncSettingDaoConfig;
    private final DaoConfig syncHistoryDaoConfig;
    private final DaoConfig partitionDaoConfig;

    private final FragmentInfoDao fragmentInfoDao;
    private final StorageDao storageDao;
    private final StatisticsDao statisticsDao;
    private final AppDao appDao;
    private final SearchDao searchDao;
    private final RecentOpenDao recentOpenDao;
    private final LabelDao labelDao;
    private final LabelFileDao labelFileDao;
    private final DownloadedFileDao downloadedFileDao;
    private final FavourateMusicDao favourateMusicDao;
    private final RecentMusicDao recentMusicDao;
    private final DownloadMusicDao downloadMusicDao;
    private final DropboxAccountDao dropboxAccountDao;
    private final WebDavAccountDao webDavAccountDao;
    private final FePrivateCloudAccountDao fePrivateCloudAccountDao;
    private final SinaStorageAccountDao sinaStorageAccountDao;
    private final DropboxFileDao dropboxFileDao;
    private final WebDavFileDao webDavFileDao;
    private final FePrivateCloudFileDao fePrivateCloudFileDao;
    private final SinaStorageFileDao sinaStorageFileDao;
    private final GoogleDriveAccountDao googleDriveAccountDao;
    private final OneDriveAccountDao oneDriveAccountDao;
    private final BoxAccountDao boxAccountDao;
    private final YandexAccountDao yandexAccountDao;
    private final SugarsyncAccountDao sugarsyncAccountDao;
    private final MixCloudAccountDao mixCloudAccountDao;
    private final GoogleDriveFileDao googleDriveFileDao;
    private final OneDriveFileDao oneDriveFileDao;
    private final BoxFileDao boxFileDao;
    private final YandexFileDao yandexFileDao;
    private final SugarsyncFileDao sugarsyncFileDao;
    private final MixCloudFileDao mixCloudFileDao;
    private final AppFolderDao appFolderDao;
    private final FtpFileInfoDao ftpFileInfoDao;
    private final FtpAccountDao ftpAccountDao;
    private final FeSmbFileDao feSmbFileDao;
    private final SmbAccountDao smbAccountDao;
    private final GCloudAccountDao gCloudAccountDao;
    private final GCloudFileDao gCloudFileDao;
    private final SyncInfoDao syncInfoDao;
    private final SyncSettingDao syncSettingDao;
    private final SyncHistoryDao syncHistoryDao;
    private final PartitionDao partitionDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        fragmentInfoDaoConfig = daoConfigMap.get(FragmentInfoDao.class).clone();
        fragmentInfoDaoConfig.initIdentityScope(type);

        storageDaoConfig = daoConfigMap.get(StorageDao.class).clone();
        storageDaoConfig.initIdentityScope(type);

        statisticsDaoConfig = daoConfigMap.get(StatisticsDao.class).clone();
        statisticsDaoConfig.initIdentityScope(type);

        appDaoConfig = daoConfigMap.get(AppDao.class).clone();
        appDaoConfig.initIdentityScope(type);

        searchDaoConfig = daoConfigMap.get(SearchDao.class).clone();
        searchDaoConfig.initIdentityScope(type);

        recentOpenDaoConfig = daoConfigMap.get(RecentOpenDao.class).clone();
        recentOpenDaoConfig.initIdentityScope(type);

        labelDaoConfig = daoConfigMap.get(LabelDao.class).clone();
        labelDaoConfig.initIdentityScope(type);

        labelFileDaoConfig = daoConfigMap.get(LabelFileDao.class).clone();
        labelFileDaoConfig.initIdentityScope(type);

        downloadedFileDaoConfig = daoConfigMap.get(DownloadedFileDao.class).clone();
        downloadedFileDaoConfig.initIdentityScope(type);

        favourateMusicDaoConfig = daoConfigMap.get(FavourateMusicDao.class).clone();
        favourateMusicDaoConfig.initIdentityScope(type);

        recentMusicDaoConfig = daoConfigMap.get(RecentMusicDao.class).clone();
        recentMusicDaoConfig.initIdentityScope(type);

        downloadMusicDaoConfig = daoConfigMap.get(DownloadMusicDao.class).clone();
        downloadMusicDaoConfig.initIdentityScope(type);

        dropboxAccountDaoConfig = daoConfigMap.get(DropboxAccountDao.class).clone();
        dropboxAccountDaoConfig.initIdentityScope(type);

        webDavAccountDaoConfig = daoConfigMap.get(WebDavAccountDao.class).clone();
        webDavAccountDaoConfig.initIdentityScope(type);

        fePrivateCloudAccountDaoConfig = daoConfigMap.get(FePrivateCloudAccountDao.class).clone();
        fePrivateCloudAccountDaoConfig.initIdentityScope(type);

        sinaStorageAccountDaoConfig = daoConfigMap.get(SinaStorageAccountDao.class).clone();
        sinaStorageAccountDaoConfig.initIdentityScope(type);

        dropboxFileDaoConfig = daoConfigMap.get(DropboxFileDao.class).clone();
        dropboxFileDaoConfig.initIdentityScope(type);

        webDavFileDaoConfig = daoConfigMap.get(WebDavFileDao.class).clone();
        webDavFileDaoConfig.initIdentityScope(type);

        fePrivateCloudFileDaoConfig = daoConfigMap.get(FePrivateCloudFileDao.class).clone();
        fePrivateCloudFileDaoConfig.initIdentityScope(type);

        sinaStorageFileDaoConfig = daoConfigMap.get(SinaStorageFileDao.class).clone();
        sinaStorageFileDaoConfig.initIdentityScope(type);

        googleDriveAccountDaoConfig = daoConfigMap.get(GoogleDriveAccountDao.class).clone();
        googleDriveAccountDaoConfig.initIdentityScope(type);

        oneDriveAccountDaoConfig = daoConfigMap.get(OneDriveAccountDao.class).clone();
        oneDriveAccountDaoConfig.initIdentityScope(type);

        boxAccountDaoConfig = daoConfigMap.get(BoxAccountDao.class).clone();
        boxAccountDaoConfig.initIdentityScope(type);

        yandexAccountDaoConfig = daoConfigMap.get(YandexAccountDao.class).clone();
        yandexAccountDaoConfig.initIdentityScope(type);

        sugarsyncAccountDaoConfig = daoConfigMap.get(SugarsyncAccountDao.class).clone();
        sugarsyncAccountDaoConfig.initIdentityScope(type);

        mixCloudAccountDaoConfig = daoConfigMap.get(MixCloudAccountDao.class).clone();
        mixCloudAccountDaoConfig.initIdentityScope(type);

        googleDriveFileDaoConfig = daoConfigMap.get(GoogleDriveFileDao.class).clone();
        googleDriveFileDaoConfig.initIdentityScope(type);

        oneDriveFileDaoConfig = daoConfigMap.get(OneDriveFileDao.class).clone();
        oneDriveFileDaoConfig.initIdentityScope(type);

        boxFileDaoConfig = daoConfigMap.get(BoxFileDao.class).clone();
        boxFileDaoConfig.initIdentityScope(type);

        yandexFileDaoConfig = daoConfigMap.get(YandexFileDao.class).clone();
        yandexFileDaoConfig.initIdentityScope(type);

        sugarsyncFileDaoConfig = daoConfigMap.get(SugarsyncFileDao.class).clone();
        sugarsyncFileDaoConfig.initIdentityScope(type);

        mixCloudFileDaoConfig = daoConfigMap.get(MixCloudFileDao.class).clone();
        mixCloudFileDaoConfig.initIdentityScope(type);

        appFolderDaoConfig = daoConfigMap.get(AppFolderDao.class).clone();
        appFolderDaoConfig.initIdentityScope(type);

        ftpFileInfoDaoConfig = daoConfigMap.get(FtpFileInfoDao.class).clone();
        ftpFileInfoDaoConfig.initIdentityScope(type);

        ftpAccountDaoConfig = daoConfigMap.get(FtpAccountDao.class).clone();
        ftpAccountDaoConfig.initIdentityScope(type);

        feSmbFileDaoConfig = daoConfigMap.get(FeSmbFileDao.class).clone();
        feSmbFileDaoConfig.initIdentityScope(type);

        smbAccountDaoConfig = daoConfigMap.get(SmbAccountDao.class).clone();
        smbAccountDaoConfig.initIdentityScope(type);

        gCloudAccountDaoConfig = daoConfigMap.get(GCloudAccountDao.class).clone();
        gCloudAccountDaoConfig.initIdentityScope(type);

        gCloudFileDaoConfig = daoConfigMap.get(GCloudFileDao.class).clone();
        gCloudFileDaoConfig.initIdentityScope(type);

        syncInfoDaoConfig = daoConfigMap.get(SyncInfoDao.class).clone();
        syncInfoDaoConfig.initIdentityScope(type);

        syncSettingDaoConfig = daoConfigMap.get(SyncSettingDao.class).clone();
        syncSettingDaoConfig.initIdentityScope(type);

        syncHistoryDaoConfig = daoConfigMap.get(SyncHistoryDao.class).clone();
        syncHistoryDaoConfig.initIdentityScope(type);

        partitionDaoConfig = daoConfigMap.get(PartitionDao.class).clone();
        partitionDaoConfig.initIdentityScope(type);

        fragmentInfoDao = new FragmentInfoDao(fragmentInfoDaoConfig, this);
        storageDao = new StorageDao(storageDaoConfig, this);
        statisticsDao = new StatisticsDao(statisticsDaoConfig, this);
        appDao = new AppDao(appDaoConfig, this);
        searchDao = new SearchDao(searchDaoConfig, this);
        recentOpenDao = new RecentOpenDao(recentOpenDaoConfig, this);
        labelDao = new LabelDao(labelDaoConfig, this);
        labelFileDao = new LabelFileDao(labelFileDaoConfig, this);
        downloadedFileDao = new DownloadedFileDao(downloadedFileDaoConfig, this);
        favourateMusicDao = new FavourateMusicDao(favourateMusicDaoConfig, this);
        recentMusicDao = new RecentMusicDao(recentMusicDaoConfig, this);
        downloadMusicDao = new DownloadMusicDao(downloadMusicDaoConfig, this);
        dropboxAccountDao = new DropboxAccountDao(dropboxAccountDaoConfig, this);
        webDavAccountDao = new WebDavAccountDao(webDavAccountDaoConfig, this);
        fePrivateCloudAccountDao = new FePrivateCloudAccountDao(fePrivateCloudAccountDaoConfig, this);
        sinaStorageAccountDao = new SinaStorageAccountDao(sinaStorageAccountDaoConfig, this);
        dropboxFileDao = new DropboxFileDao(dropboxFileDaoConfig, this);
        webDavFileDao = new WebDavFileDao(webDavFileDaoConfig, this);
        fePrivateCloudFileDao = new FePrivateCloudFileDao(fePrivateCloudFileDaoConfig, this);
        sinaStorageFileDao = new SinaStorageFileDao(sinaStorageFileDaoConfig, this);
        googleDriveAccountDao = new GoogleDriveAccountDao(googleDriveAccountDaoConfig, this);
        oneDriveAccountDao = new OneDriveAccountDao(oneDriveAccountDaoConfig, this);
        boxAccountDao = new BoxAccountDao(boxAccountDaoConfig, this);
        yandexAccountDao = new YandexAccountDao(yandexAccountDaoConfig, this);
        sugarsyncAccountDao = new SugarsyncAccountDao(sugarsyncAccountDaoConfig, this);
        mixCloudAccountDao = new MixCloudAccountDao(mixCloudAccountDaoConfig, this);
        googleDriveFileDao = new GoogleDriveFileDao(googleDriveFileDaoConfig, this);
        oneDriveFileDao = new OneDriveFileDao(oneDriveFileDaoConfig, this);
        boxFileDao = new BoxFileDao(boxFileDaoConfig, this);
        yandexFileDao = new YandexFileDao(yandexFileDaoConfig, this);
        sugarsyncFileDao = new SugarsyncFileDao(sugarsyncFileDaoConfig, this);
        mixCloudFileDao = new MixCloudFileDao(mixCloudFileDaoConfig, this);
        appFolderDao = new AppFolderDao(appFolderDaoConfig, this);
        ftpFileInfoDao = new FtpFileInfoDao(ftpFileInfoDaoConfig, this);
        ftpAccountDao = new FtpAccountDao(ftpAccountDaoConfig, this);
        feSmbFileDao = new FeSmbFileDao(feSmbFileDaoConfig, this);
        smbAccountDao = new SmbAccountDao(smbAccountDaoConfig, this);
        gCloudAccountDao = new GCloudAccountDao(gCloudAccountDaoConfig, this);
        gCloudFileDao = new GCloudFileDao(gCloudFileDaoConfig, this);
        syncInfoDao = new SyncInfoDao(syncInfoDaoConfig, this);
        syncSettingDao = new SyncSettingDao(syncSettingDaoConfig, this);
        syncHistoryDao = new SyncHistoryDao(syncHistoryDaoConfig, this);
        partitionDao = new PartitionDao(partitionDaoConfig, this);

        registerDao(FragmentInfo.class, fragmentInfoDao);
        registerDao(Storage.class, storageDao);
        registerDao(Statistics.class, statisticsDao);
        registerDao(App.class, appDao);
        registerDao(Search.class, searchDao);
        registerDao(RecentOpen.class, recentOpenDao);
        registerDao(Label.class, labelDao);
        registerDao(LabelFile.class, labelFileDao);
        registerDao(DownloadedFile.class, downloadedFileDao);
        registerDao(FavourateMusic.class, favourateMusicDao);
        registerDao(RecentMusic.class, recentMusicDao);
        registerDao(DownloadMusic.class, downloadMusicDao);
        registerDao(DropboxAccount.class, dropboxAccountDao);
        registerDao(WebDavAccount.class, webDavAccountDao);
        registerDao(FePrivateCloudAccount.class, fePrivateCloudAccountDao);
        registerDao(SinaStorageAccount.class, sinaStorageAccountDao);
        registerDao(DropboxFile.class, dropboxFileDao);
        registerDao(WebDavFile.class, webDavFileDao);
        registerDao(FePrivateCloudFile.class, fePrivateCloudFileDao);
        registerDao(SinaStorageFile.class, sinaStorageFileDao);
        registerDao(GoogleDriveAccount.class, googleDriveAccountDao);
        registerDao(OneDriveAccount.class, oneDriveAccountDao);
        registerDao(BoxAccount.class, boxAccountDao);
        registerDao(YandexAccount.class, yandexAccountDao);
        registerDao(SugarsyncAccount.class, sugarsyncAccountDao);
        registerDao(MixCloudAccount.class, mixCloudAccountDao);
        registerDao(GoogleDriveFile.class, googleDriveFileDao);
        registerDao(OneDriveFile.class, oneDriveFileDao);
        registerDao(BoxFile.class, boxFileDao);
        registerDao(YandexFile.class, yandexFileDao);
        registerDao(SugarsyncFile.class, sugarsyncFileDao);
        registerDao(MixCloudFile.class, mixCloudFileDao);
        registerDao(AppFolder.class, appFolderDao);
        registerDao(FtpFileInfo.class, ftpFileInfoDao);
        registerDao(FtpAccount.class, ftpAccountDao);
        registerDao(FeSmbFile.class, feSmbFileDao);
        registerDao(SmbAccount.class, smbAccountDao);
        registerDao(GCloudAccount.class, gCloudAccountDao);
        registerDao(GCloudFile.class, gCloudFileDao);
        registerDao(SyncInfo.class, syncInfoDao);
        registerDao(SyncSetting.class, syncSettingDao);
        registerDao(SyncHistory.class, syncHistoryDao);
        registerDao(Partition.class, partitionDao);
    }
    
    public void clear() {
        fragmentInfoDaoConfig.getIdentityScope().clear();
        storageDaoConfig.getIdentityScope().clear();
        statisticsDaoConfig.getIdentityScope().clear();
        appDaoConfig.getIdentityScope().clear();
        searchDaoConfig.getIdentityScope().clear();
        recentOpenDaoConfig.getIdentityScope().clear();
        labelDaoConfig.getIdentityScope().clear();
        labelFileDaoConfig.getIdentityScope().clear();
        downloadedFileDaoConfig.getIdentityScope().clear();
        favourateMusicDaoConfig.getIdentityScope().clear();
        recentMusicDaoConfig.getIdentityScope().clear();
        downloadMusicDaoConfig.getIdentityScope().clear();
        dropboxAccountDaoConfig.getIdentityScope().clear();
        webDavAccountDaoConfig.getIdentityScope().clear();
        fePrivateCloudAccountDaoConfig.getIdentityScope().clear();
        sinaStorageAccountDaoConfig.getIdentityScope().clear();
        dropboxFileDaoConfig.getIdentityScope().clear();
        webDavFileDaoConfig.getIdentityScope().clear();
        fePrivateCloudFileDaoConfig.getIdentityScope().clear();
        sinaStorageFileDaoConfig.getIdentityScope().clear();
        googleDriveAccountDaoConfig.getIdentityScope().clear();
        oneDriveAccountDaoConfig.getIdentityScope().clear();
        boxAccountDaoConfig.getIdentityScope().clear();
        yandexAccountDaoConfig.getIdentityScope().clear();
        sugarsyncAccountDaoConfig.getIdentityScope().clear();
        mixCloudAccountDaoConfig.getIdentityScope().clear();
        googleDriveFileDaoConfig.getIdentityScope().clear();
        oneDriveFileDaoConfig.getIdentityScope().clear();
        boxFileDaoConfig.getIdentityScope().clear();
        yandexFileDaoConfig.getIdentityScope().clear();
        sugarsyncFileDaoConfig.getIdentityScope().clear();
        mixCloudFileDaoConfig.getIdentityScope().clear();
        appFolderDaoConfig.getIdentityScope().clear();
        ftpFileInfoDaoConfig.getIdentityScope().clear();
        ftpAccountDaoConfig.getIdentityScope().clear();
        feSmbFileDaoConfig.getIdentityScope().clear();
        smbAccountDaoConfig.getIdentityScope().clear();
        gCloudAccountDaoConfig.getIdentityScope().clear();
        gCloudFileDaoConfig.getIdentityScope().clear();
        syncInfoDaoConfig.getIdentityScope().clear();
        syncSettingDaoConfig.getIdentityScope().clear();
        syncHistoryDaoConfig.getIdentityScope().clear();
        partitionDaoConfig.getIdentityScope().clear();
    }

    public FragmentInfoDao getFragmentInfoDao() {
        return fragmentInfoDao;
    }

    public StorageDao getStorageDao() {
        return storageDao;
    }

    public StatisticsDao getStatisticsDao() {
        return statisticsDao;
    }

    public AppDao getAppDao() {
        return appDao;
    }

    public SearchDao getSearchDao() {
        return searchDao;
    }

    public RecentOpenDao getRecentOpenDao() {
        return recentOpenDao;
    }

    public LabelDao getLabelDao() {
        return labelDao;
    }

    public LabelFileDao getLabelFileDao() {
        return labelFileDao;
    }

    public DownloadedFileDao getDownloadedFileDao() {
        return downloadedFileDao;
    }

    public FavourateMusicDao getFavourateMusicDao() {
        return favourateMusicDao;
    }

    public RecentMusicDao getRecentMusicDao() {
        return recentMusicDao;
    }

    public DownloadMusicDao getDownloadMusicDao() {
        return downloadMusicDao;
    }

    public DropboxAccountDao getDropboxAccountDao() {
        return dropboxAccountDao;
    }

    public WebDavAccountDao getWebDavAccountDao() {
        return webDavAccountDao;
    }

    public FePrivateCloudAccountDao getFePrivateCloudAccountDao() {
        return fePrivateCloudAccountDao;
    }

    public SinaStorageAccountDao getSinaStorageAccountDao() {
        return sinaStorageAccountDao;
    }

    public DropboxFileDao getDropboxFileDao() {
        return dropboxFileDao;
    }

    public WebDavFileDao getWebDavFileDao() {
        return webDavFileDao;
    }

    public FePrivateCloudFileDao getFePrivateCloudFileDao() {
        return fePrivateCloudFileDao;
    }

    public SinaStorageFileDao getSinaStorageFileDao() {
        return sinaStorageFileDao;
    }

    public GoogleDriveAccountDao getGoogleDriveAccountDao() {
        return googleDriveAccountDao;
    }

    public OneDriveAccountDao getOneDriveAccountDao() {
        return oneDriveAccountDao;
    }

    public BoxAccountDao getBoxAccountDao() {
        return boxAccountDao;
    }

    public YandexAccountDao getYandexAccountDao() {
        return yandexAccountDao;
    }

    public SugarsyncAccountDao getSugarsyncAccountDao() {
        return sugarsyncAccountDao;
    }

    public MixCloudAccountDao getMixCloudAccountDao() {
        return mixCloudAccountDao;
    }

    public GoogleDriveFileDao getGoogleDriveFileDao() {
        return googleDriveFileDao;
    }

    public OneDriveFileDao getOneDriveFileDao() {
        return oneDriveFileDao;
    }

    public BoxFileDao getBoxFileDao() {
        return boxFileDao;
    }

    public YandexFileDao getYandexFileDao() {
        return yandexFileDao;
    }

    public SugarsyncFileDao getSugarsyncFileDao() {
        return sugarsyncFileDao;
    }

    public MixCloudFileDao getMixCloudFileDao() {
        return mixCloudFileDao;
    }

    public AppFolderDao getAppFolderDao() {
        return appFolderDao;
    }

    public FtpFileInfoDao getFtpFileInfoDao() {
        return ftpFileInfoDao;
    }

    public FtpAccountDao getFtpAccountDao() {
        return ftpAccountDao;
    }

    public FeSmbFileDao getFeSmbFileDao() {
        return feSmbFileDao;
    }

    public SmbAccountDao getSmbAccountDao() {
        return smbAccountDao;
    }

    public GCloudAccountDao getGCloudAccountDao() {
        return gCloudAccountDao;
    }

    public GCloudFileDao getGCloudFileDao() {
        return gCloudFileDao;
    }

    public SyncInfoDao getSyncInfoDao() {
        return syncInfoDao;
    }

    public SyncSettingDao getSyncSettingDao() {
        return syncSettingDao;
    }

    public SyncHistoryDao getSyncHistoryDao() {
        return syncHistoryDao;
    }

    public PartitionDao getPartitionDao() {
        return partitionDao;
    }

}
