package com.grt.filemanager.orm.dao.base;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import com.grt.filemanager.orm.dao.WebDavAccount;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "WEB_DAV_ACCOUNT".
*/
public class WebDavAccountDao extends AbstractDao<WebDavAccount, Long> {

    public static final String TABLENAME = "WEB_DAV_ACCOUNT";

    /**
     * Properties of entity WebDavAccount.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Protocol = new Property(1, String.class, "protocol", false, "PROTOCOL");
        public final static Property Hostname = new Property(2, String.class, "hostname", false, "HOSTNAME");
        public final static Property Port = new Property(3, Integer.class, "port", false, "PORT");
        public final static Property Account = new Property(4, String.class, "account", false, "ACCOUNT");
        public final static Property Password = new Property(5, String.class, "password", false, "PASSWORD");
        public final static Property Anonymous = new Property(6, Boolean.class, "anonymous", false, "ANONYMOUS");
        public final static Property Token = new Property(7, String.class, "token", false, "TOKEN");
        public final static Property RefreshToken = new Property(8, String.class, "refreshToken", false, "REFRESH_TOKEN");
        public final static Property TotalSize = new Property(9, Long.class, "totalSize", false, "TOTAL_SIZE");
        public final static Property LeftSize = new Property(10, Long.class, "leftSize", false, "LEFT_SIZE");
        public final static Property LoginTime = new Property(11, Long.class, "loginTime", false, "LOGIN_TIME");
    };


    public WebDavAccountDao(DaoConfig config) {
        super(config);
    }
    
    public WebDavAccountDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"WEB_DAV_ACCOUNT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"PROTOCOL\" TEXT," + // 1: protocol
                "\"HOSTNAME\" TEXT," + // 2: hostname
                "\"PORT\" INTEGER," + // 3: port
                "\"ACCOUNT\" TEXT," + // 4: account
                "\"PASSWORD\" TEXT," + // 5: password
                "\"ANONYMOUS\" INTEGER," + // 6: anonymous
                "\"TOKEN\" TEXT," + // 7: token
                "\"REFRESH_TOKEN\" TEXT," + // 8: refreshToken
                "\"TOTAL_SIZE\" INTEGER," + // 9: totalSize
                "\"LEFT_SIZE\" INTEGER," + // 10: leftSize
                "\"LOGIN_TIME\" INTEGER);"); // 11: loginTime
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_WEB_DAV_ACCOUNT_PROTOCOL_HOSTNAME_PORT_ACCOUNT ON WEB_DAV_ACCOUNT" +
                " (\"PROTOCOL\",\"HOSTNAME\",\"PORT\",\"ACCOUNT\");");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"WEB_DAV_ACCOUNT\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, WebDavAccount entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String protocol = entity.getProtocol();
        if (protocol != null) {
            stmt.bindString(2, protocol);
        }
 
        String hostname = entity.getHostname();
        if (hostname != null) {
            stmt.bindString(3, hostname);
        }
 
        Integer port = entity.getPort();
        if (port != null) {
            stmt.bindLong(4, port);
        }
 
        String account = entity.getAccount();
        if (account != null) {
            stmt.bindString(5, account);
        }
 
        String password = entity.getPassword();
        if (password != null) {
            stmt.bindString(6, password);
        }
 
        Boolean anonymous = entity.getAnonymous();
        if (anonymous != null) {
            stmt.bindLong(7, anonymous ? 1L: 0L);
        }
 
        String token = entity.getToken();
        if (token != null) {
            stmt.bindString(8, token);
        }
 
        String refreshToken = entity.getRefreshToken();
        if (refreshToken != null) {
            stmt.bindString(9, refreshToken);
        }
 
        Long totalSize = entity.getTotalSize();
        if (totalSize != null) {
            stmt.bindLong(10, totalSize);
        }
 
        Long leftSize = entity.getLeftSize();
        if (leftSize != null) {
            stmt.bindLong(11, leftSize);
        }
 
        Long loginTime = entity.getLoginTime();
        if (loginTime != null) {
            stmt.bindLong(12, loginTime);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public WebDavAccount readEntity(Cursor cursor, int offset) {
        WebDavAccount entity = new WebDavAccount( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // protocol
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // hostname
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // port
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // account
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // password
            cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6) != 0, // anonymous
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // token
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // refreshToken
            cursor.isNull(offset + 9) ? null : cursor.getLong(offset + 9), // totalSize
            cursor.isNull(offset + 10) ? null : cursor.getLong(offset + 10), // leftSize
            cursor.isNull(offset + 11) ? null : cursor.getLong(offset + 11) // loginTime
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, WebDavAccount entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setProtocol(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setHostname(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPort(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setAccount(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setPassword(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setAnonymous(cursor.isNull(offset + 6) ? null : cursor.getShort(offset + 6) != 0);
        entity.setToken(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setRefreshToken(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setTotalSize(cursor.isNull(offset + 9) ? null : cursor.getLong(offset + 9));
        entity.setLeftSize(cursor.isNull(offset + 10) ? null : cursor.getLong(offset + 10));
        entity.setLoginTime(cursor.isNull(offset + 11) ? null : cursor.getLong(offset + 11));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(WebDavAccount entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(WebDavAccount entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
