package com.grt.filemanager.orm.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "APP_FOLDER".
 */
public class AppFolder {

    private Long id;
    /** Not-null value. */
    private String folder;
    /** Not-null value. */
    private String packageName;

    public AppFolder() {
    }

    public AppFolder(Long id) {
        this.id = id;
    }

    public AppFolder(Long id, String folder, String packageName) {
        this.id = id;
        this.folder = folder;
        this.packageName = packageName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getFolder() {
        return folder;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFolder(String folder) {
        this.folder = folder;
    }

    /** Not-null value. */
    public String getPackageName() {
        return packageName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPackageName(String packageName) {
        this.packageName = packageName;
    }

}
