package com.grt.filemanager.orm.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "BOX_FILE".
 */
public class BoxFile {

    private Long id;
    private String name;
    private String path;
    private Long size;
    private String mimeType;
    private Long lastModified;
    private Boolean isFolder;
    private Integer accountId;
    private String etag;
    private String parentId;
    private String fileId;

    public BoxFile() {
    }

    public BoxFile(Long id) {
        this.id = id;
    }

    public BoxFile(Long id, String name, String path, Long size, String mimeType, Long lastModified, Boolean isFolder, Integer accountId, String etag, String parentId, String fileId) {
        this.id = id;
        this.name = name;
        this.path = path;
        this.size = size;
        this.mimeType = mimeType;
        this.lastModified = lastModified;
        this.isFolder = isFolder;
        this.accountId = accountId;
        this.etag = etag;
        this.parentId = parentId;
        this.fileId = fileId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public Long getSize() {
        return size;
    }

    public void setSize(Long size) {
        this.size = size;
    }

    public String getMimeType() {
        return mimeType;
    }

    public void setMimeType(String mimeType) {
        this.mimeType = mimeType;
    }

    public Long getLastModified() {
        return lastModified;
    }

    public void setLastModified(Long lastModified) {
        this.lastModified = lastModified;
    }

    public Boolean getIsFolder() {
        return isFolder;
    }

    public void setIsFolder(Boolean isFolder) {
        this.isFolder = isFolder;
    }

    public Integer getAccountId() {
        return accountId;
    }

    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    public String getEtag() {
        return etag;
    }

    public void setEtag(String etag) {
        this.etag = etag;
    }

    public String getParentId() {
        return parentId;
    }

    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    public String getFileId() {
        return fileId;
    }

    public void setFileId(String fileId) {
        this.fileId = fileId;
    }

    @Override
    public String toString() {
        return "BoxFile{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", path='" + path + '\'' +
                ", size=" + size +
                ", mimeType='" + mimeType + '\'' +
                ", lastModified=" + lastModified +
                ", isFolder=" + isFolder +
                ", accountId=" + accountId +
                ", etag='" + etag + '\'' +
                ", parentId='" + parentId + '\'' +
                ", fileId='" + fileId + '\'' +
                '}';
    }
}
