package com.grt.filemanager.orm.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "FE_SMB_FILE".
 */
public class FeSmbFile {

    private Long id;
    private String name;
    /** Not-null value. */
    private String path;
    private long lastModified;
    private long size;
    /** Not-null value. */
    private String mimeType;
    private boolean isFolder;
    private int count;
    private long parentId;
    private int accountId;
    /** Not-null value. */
    private String cachePath;

    public FeSmbFile() {
    }

    public FeSmbFile(Long id) {
        this.id = id;
    }

    public FeSmbFile(Long id, String name, String path, long lastModified, long size, String mimeType, boolean isFolder, int count, long parentId, int accountId, String cachePath) {
        this.id = id;
        this.name = name;
        this.path = path;
        this.lastModified = lastModified;
        this.size = size;
        this.mimeType = mimeType;
        this.isFolder = isFolder;
        this.count = count;
        this.parentId = parentId;
        this.accountId = accountId;
        this.cachePath = cachePath;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getPath() {
        return path;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPath(String path) {
        this.path = path;
    }

    public long getLastModified() {
        return lastModified;
    }

    public void setLastModified(long lastModified) {
        this.lastModified = lastModified;
    }

    public long getSize() {
        return size;
    }

    public void setSize(long size) {
        this.size = size;
    }

    /** Not-null value. */
    public String getMimeType() {
        return mimeType;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMimeType(String mimeType) {
        this.mimeType = mimeType;
    }

    public boolean getIsFolder() {
        return isFolder;
    }

    public void setIsFolder(boolean isFolder) {
        this.isFolder = isFolder;
    }

    public int getCount() {
        return count;
    }

    public void setCount(int count) {
        this.count = count;
    }

    public long getParentId() {
        return parentId;
    }

    public void setParentId(long parentId) {
        this.parentId = parentId;
    }

    public int getAccountId() {
        return accountId;
    }

    public void setAccountId(int accountId) {
        this.accountId = accountId;
    }

    /** Not-null value. */
    public String getCachePath() {
        return cachePath;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCachePath(String cachePath) {
        this.cachePath = cachePath;
    }

}
