package com.grt.filemanager.orm.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "FTP_ACCOUNT".
 */
public class FtpAccount {

    private Long id;
    private Integer type;
    private String serveraddress;
    private Integer port;
    private String encoding;
    private Integer connectmode;
    private String byname;
    private String account;
    private String password;
    private Integer anonymous;

    public FtpAccount() {
    }

    public FtpAccount(Long id) {
        this.id = id;
    }

    public FtpAccount(Long id, Integer type, String serveraddress, Integer port, String encoding, Integer connectmode, String byname, String account, String password, Integer anonymous) {
        this.id = id;
        this.type = type;
        this.serveraddress = serveraddress;
        this.port = port;
        this.encoding = encoding;
        this.connectmode = connectmode;
        this.byname = byname;
        this.account = account;
        this.password = password;
        this.anonymous = anonymous;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public String getServeraddress() {
        return serveraddress;
    }

    public void setServeraddress(String serveraddress) {
        this.serveraddress = serveraddress;
    }

    public Integer getPort() {
        return port;
    }

    public void setPort(Integer port) {
        this.port = port;
    }

    public String getEncoding() {
        return encoding;
    }

    public void setEncoding(String encoding) {
        this.encoding = encoding;
    }

    public Integer getConnectmode() {
        return connectmode;
    }

    public void setConnectmode(Integer connectmode) {
        this.connectmode = connectmode;
    }

    public String getByname() {
        return byname;
    }

    public void setByname(String byname) {
        this.byname = byname;
    }

    public String getAccount() {
        return account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Integer getAnonymous() {
        return anonymous;
    }

    public void setAnonymous(Integer anonymous) {
        this.anonymous = anonymous;
    }

}
