package com.grt.filemanager.orm.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GCLOUD_ACCOUNT".
 */
public class GCloudAccount {

    private Long id;
    private String account;
    private String feAccount;
    private String token;
    private String refreshToken;
    private Long totalSize;
    private Long leftSize;
    private Long loginTime;

    public GCloudAccount() {
    }

    public GCloudAccount(Long id) {
        this.id = id;
    }

    public GCloudAccount(Long id, String account, String feAccount, String token, String refreshToken, Long totalSize, Long leftSize, Long loginTime) {
        this.id = id;
        this.account = account;
        this.feAccount = feAccount;
        this.token = token;
        this.refreshToken = refreshToken;
        this.totalSize = totalSize;
        this.leftSize = leftSize;
        this.loginTime = loginTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAccount() {
        return account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    public String getFeAccount() {
        return feAccount;
    }

    public void setFeAccount(String feAccount) {
        this.feAccount = feAccount;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public String getRefreshToken() {
        return refreshToken;
    }

    public void setRefreshToken(String refreshToken) {
        this.refreshToken = refreshToken;
    }

    public Long getTotalSize() {
        return totalSize;
    }

    public void setTotalSize(Long totalSize) {
        this.totalSize = totalSize;
    }

    public Long getLeftSize() {
        return leftSize;
    }

    public void setLeftSize(Long leftSize) {
        this.leftSize = leftSize;
    }

    public Long getLoginTime() {
        return loginTime;
    }

    public void setLoginTime(Long loginTime) {
        this.loginTime = loginTime;
    }

}
