package com.grt.filemanager.orm.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GCLOUD_FILE".
 */
public class GCloudFile {

    private Long id;
    private String name;
    private String path;
    private Long size;
    private String mimeType;
    private Long lastModified;
    private Boolean isFolder;
    private String parentId;
    private String fileId;
    private String folder;
    private String url;
    private String thumbUrl;
    private String versionName;
    private String versionCode;
    private String packageName;
    private String dataUrl;
    private Integer dataSize;
    private Integer status;

    public GCloudFile() {
    }

    public GCloudFile(Long id) {
        this.id = id;
    }

    public GCloudFile(Long id, String name, String path, Long size, String mimeType, Long lastModified, Boolean isFolder, String parentId, String fileId, String folder, String url, String thumbUrl, String versionName, String versionCode, String packageName, String dataUrl, Integer dataSize, Integer status) {
        this.id = id;
        this.name = name;
        this.path = path;
        this.size = size;
        this.mimeType = mimeType;
        this.lastModified = lastModified;
        this.isFolder = isFolder;
        this.parentId = parentId;
        this.fileId = fileId;
        this.folder = folder;
        this.url = url;
        this.thumbUrl = thumbUrl;
        this.versionName = versionName;
        this.versionCode = versionCode;
        this.packageName = packageName;
        this.dataUrl = dataUrl;
        this.dataSize = dataSize;
        this.status = status;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public Long getSize() {
        return size;
    }

    public void setSize(Long size) {
        this.size = size;
    }

    public String getMimeType() {
        return mimeType;
    }

    public void setMimeType(String mimeType) {
        this.mimeType = mimeType;
    }

    public Long getLastModified() {
        return lastModified;
    }

    public void setLastModified(Long lastModified) {
        this.lastModified = lastModified;
    }

    public Boolean getIsFolder() {
        return isFolder;
    }

    public void setIsFolder(Boolean isFolder) {
        this.isFolder = isFolder;
    }

    public String getParentId() {
        return parentId;
    }

    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    public String getFileId() {
        return fileId;
    }

    public void setFileId(String fileId) {
        this.fileId = fileId;
    }

    public String getFolder() {
        return folder;
    }

    public void setFolder(String folder) {
        this.folder = folder;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getThumbUrl() {
        return thumbUrl;
    }

    public void setThumbUrl(String thumbUrl) {
        this.thumbUrl = thumbUrl;
    }

    public String getVersionName() {
        return versionName;
    }

    public void setVersionName(String versionName) {
        this.versionName = versionName;
    }

    public String getVersionCode() {
        return versionCode;
    }

    public void setVersionCode(String versionCode) {
        this.versionCode = versionCode;
    }

    public String getPackageName() {
        return packageName;
    }

    public void setPackageName(String packageName) {
        this.packageName = packageName;
    }

    public String getDataUrl() {
        return dataUrl;
    }

    public void setDataUrl(String dataUrl) {
        this.dataUrl = dataUrl;
    }

    public Integer getDataSize() {
        return dataSize;
    }

    public void setDataSize(Integer dataSize) {
        this.dataSize = dataSize;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

}
