package com.grt.filemanager.orm.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "LABEL_FILE".
 */
public class LabelFile {

    private Long id;
    private String name;
    private String path;
    private Long size;
    private Long date_modified;
    private Long labelId;
    private String mime_type;
    private Boolean is_file;

    public LabelFile() {
    }

    public LabelFile(Long id) {
        this.id = id;
    }

    public LabelFile(Long id, String name, String path, Long size, Long date_modified, Long labelId, String mime_type, Boolean is_file) {
        this.id = id;
        this.name = name;
        this.path = path;
        this.size = size;
        this.date_modified = date_modified;
        this.labelId = labelId;
        this.mime_type = mime_type;
        this.is_file = is_file;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public Long getSize() {
        return size;
    }

    public void setSize(Long size) {
        this.size = size;
    }

    public Long getDate_modified() {
        return date_modified;
    }

    public void setDate_modified(Long date_modified) {
        this.date_modified = date_modified;
    }

    public Long getLabelId() {
        return labelId;
    }

    public void setLabelId(Long labelId) {
        this.labelId = labelId;
    }

    public String getMime_type() {
        return mime_type;
    }

    public void setMime_type(String mime_type) {
        this.mime_type = mime_type;
    }

    public Boolean getIs_file() {
        return is_file;
    }

    public void setIs_file(Boolean is_file) {
        this.is_file = is_file;
    }

}
