package com.grt.filemanager.orm.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PARTITION".
 */
public class Partition {

    private Long id;
    private Integer type;
    private String srcList;
    private String desFolder;
    private String name;
    private Long size;
    private String time;
    private Integer task;
    private String tmpFolder;
    private String privateKey;
    private String cloud;
    private String account;
    private String status;
    private String localSlice;
    private String cloudSlice;
    private String downloadInfo;
    private Integer encryptNum;

    public Partition() {
    }

    public Partition(Long id) {
        this.id = id;
    }

    public Partition(Long id, Integer type, String srcList, String desFolder, String name, Long size, String time, Integer task, String tmpFolder, String privateKey, String cloud, String account, String status, String localSlice, String cloudSlice, String downloadInfo, Integer encryptNum) {
        this.id = id;
        this.type = type;
        this.srcList = srcList;
        this.desFolder = desFolder;
        this.name = name;
        this.size = size;
        this.time = time;
        this.task = task;
        this.tmpFolder = tmpFolder;
        this.privateKey = privateKey;
        this.cloud = cloud;
        this.account = account;
        this.status = status;
        this.localSlice = localSlice;
        this.cloudSlice = cloudSlice;
        this.downloadInfo = downloadInfo;
        this.encryptNum = encryptNum;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public String getSrcList() {
        return srcList;
    }

    public void setSrcList(String srcList) {
        this.srcList = srcList;
    }

    public String getDesFolder() {
        return desFolder;
    }

    public void setDesFolder(String desFolder) {
        this.desFolder = desFolder;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getSize() {
        return size;
    }

    public void setSize(Long size) {
        this.size = size;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public Integer getTask() {
        return task;
    }

    public void setTask(Integer task) {
        this.task = task;
    }

    public String getTmpFolder() {
        return tmpFolder;
    }

    public void setTmpFolder(String tmpFolder) {
        this.tmpFolder = tmpFolder;
    }

    public String getPrivateKey() {
        return privateKey;
    }

    public void setPrivateKey(String privateKey) {
        this.privateKey = privateKey;
    }

    public String getCloud() {
        return cloud;
    }

    public void setCloud(String cloud) {
        this.cloud = cloud;
    }

    public String getAccount() {
        return account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getLocalSlice() {
        return localSlice;
    }

    public void setLocalSlice(String localSlice) {
        this.localSlice = localSlice;
    }

    public String getCloudSlice() {
        return cloudSlice;
    }

    public void setCloudSlice(String cloudSlice) {
        this.cloudSlice = cloudSlice;
    }

    public String getDownloadInfo() {
        return downloadInfo;
    }

    public void setDownloadInfo(String downloadInfo) {
        this.downloadInfo = downloadInfo;
    }

    public Integer getEncryptNum() {
        return encryptNum;
    }

    public void setEncryptNum(Integer encryptNum) {
        this.encryptNum = encryptNum;
    }

    @Override
    public String toString() {
        return "Partition{" +
                "id=" + id +
                ", type=" + type +
                ", srcList='" + srcList + '\'' +
                ", desFolder='" + desFolder + '\'' +
                ", name='" + name + '\'' +
                ", size=" + size +
                ", time='" + time + '\'' +
                ", task=" + task +
                ", tmpFolder='" + tmpFolder + '\'' +
                ", privateKey='" + privateKey + '\'' +
                ", cloud='" + cloud + '\'' +
                ", account='" + account + '\'' +
                ", status='" + status + '\'' +
                ", localSlice='" + localSlice + '\'' +
                ", cloudSlice='" + cloudSlice + '\'' +
                ", downloadInfo='" + downloadInfo + '\'' +
                ", encryptNum=" + encryptNum +
                '}';
    }
}
