package com.grt.filemanager.orm.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SINA_STORAGE_FILE".
 */
public class SinaStorageFile {

    private Long id;
    private String name;
    private String path;
    private Long size;
    private String mimeType;
    private Long lastModified;
    private Boolean isFolder;
    private Integer accountId;
    private Long parentId;

    public SinaStorageFile() {
    }

    public SinaStorageFile(Long id) {
        this.id = id;
    }

    public SinaStorageFile(Long id, String name, String path, Long size, String mimeType, Long lastModified, Boolean isFolder, Integer accountId, Long parentId) {
        this.id = id;
        this.name = name;
        this.path = path;
        this.size = size;
        this.mimeType = mimeType;
        this.lastModified = lastModified;
        this.isFolder = isFolder;
        this.accountId = accountId;
        this.parentId = parentId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public Long getSize() {
        return size;
    }

    public void setSize(Long size) {
        this.size = size;
    }

    public String getMimeType() {
        return mimeType;
    }

    public void setMimeType(String mimeType) {
        this.mimeType = mimeType;
    }

    public Long getLastModified() {
        return lastModified;
    }

    public void setLastModified(Long lastModified) {
        this.lastModified = lastModified;
    }

    public Boolean getIsFolder() {
        return isFolder;
    }

    public void setIsFolder(Boolean isFolder) {
        this.isFolder = isFolder;
    }

    public Integer getAccountId() {
        return accountId;
    }

    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    public Long getParentId() {
        return parentId;
    }

    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

}
