package com.grt.filemanager.orm.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SMB_ACCOUNT".
 */
public class SmbAccount {

    private Long id;
    private String domainname;
    private String serveraddress;
    private String account;
    private String password;
    private String byname;
    private String anonymous;
    private String isscan;
    private String islogin;
    private String loginPath;
    private Long loginTime;
    private String pcname;

    public SmbAccount() {
    }

    public SmbAccount(Long id) {
        this.id = id;
    }

    public SmbAccount(Long id, String domainname, String serveraddress, String account, String password, String byname, String anonymous, String isscan, String islogin, String loginPath, Long loginTime, String pcname) {
        this.id = id;
        this.domainname = domainname;
        this.serveraddress = serveraddress;
        this.account = account;
        this.password = password;
        this.byname = byname;
        this.anonymous = anonymous;
        this.isscan = isscan;
        this.islogin = islogin;
        this.loginPath = loginPath;
        this.loginTime = loginTime;
        this.pcname = pcname;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDomainname() {
        return domainname;
    }

    public void setDomainname(String domainname) {
        this.domainname = domainname;
    }

    public String getServeraddress() {
        return serveraddress;
    }

    public void setServeraddress(String serveraddress) {
        this.serveraddress = serveraddress;
    }

    public String getAccount() {
        return account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getByname() {
        return byname;
    }

    public void setByname(String byname) {
        this.byname = byname;
    }

    public String getAnonymous() {
        return anonymous;
    }

    public void setAnonymous(String anonymous) {
        this.anonymous = anonymous;
    }

    public String getIsscan() {
        return isscan;
    }

    public void setIsscan(String isscan) {
        this.isscan = isscan;
    }

    public String getIslogin() {
        return islogin;
    }

    public void setIslogin(String islogin) {
        this.islogin = islogin;
    }

    public String getLoginPath() {
        return loginPath;
    }

    public void setLoginPath(String loginPath) {
        this.loginPath = loginPath;
    }

    public Long getLoginTime() {
        return loginTime;
    }

    public void setLoginTime(Long loginTime) {
        this.loginTime = loginTime;
    }

    public String getPcname() {
        return pcname;
    }

    public void setPcname(String pcname) {
        this.pcname = pcname;
    }

}
