package com.grt.filemanager.orm.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "STATISTICS".
 */
public class Statistics {

    private Long id;
    private String keyName;
    private String value;
    private String time;
    private String flag;

    public Statistics() {
    }

    public Statistics(Long id) {
        this.id = id;
    }

    public Statistics(Long id, String keyName, String value, String time, String flag) {
        this.id = id;
        this.keyName = keyName;
        this.value = value;
        this.time = time;
        this.flag = flag;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getKeyName() {
        return keyName;
    }

    public void setKeyName(String keyName) {
        this.keyName = keyName;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public String getFlag() {
        return flag;
    }

    public void setFlag(String flag) {
        this.flag = flag;
    }

}
