package com.grt.filemanager.orm.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "STORAGE".
 */
public class Storage {

    private Long id;
    private String path;
    private Long childrenSize;
    private Integer childrenCount;

    public Storage() {
    }

    public Storage(Long id) {
        this.id = id;
    }

    public Storage(Long id, String path, Long childrenSize, Integer childrenCount) {
        this.id = id;
        this.path = path;
        this.childrenSize = childrenSize;
        this.childrenCount = childrenCount;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public Long getChildrenSize() {
        return childrenSize;
    }

    public void setChildrenSize(Long childrenSize) {
        this.childrenSize = childrenSize;
    }

    public Integer getChildrenCount() {
        return childrenCount;
    }

    public void setChildrenCount(Integer childrenCount) {
        this.childrenCount = childrenCount;
    }

}
