package com.grt.filemanager.orm.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SUGARSYNC_ACCOUNT".
 */
public class SugarsyncAccount {

    private Long id;
    private String account;
    private String token;
    private String refreshToken;
    private Long totalSize;
    private Long leftSize;
    private Long loginTime;
    private String use_url;

    public SugarsyncAccount() {
    }

    public SugarsyncAccount(Long id) {
        this.id = id;
    }

    public SugarsyncAccount(Long id, String account, String token, String refreshToken, Long totalSize, Long leftSize, Long loginTime, String use_url) {
        this.id = id;
        this.account = account;
        this.token = token;
        this.refreshToken = refreshToken;
        this.totalSize = totalSize;
        this.leftSize = leftSize;
        this.loginTime = loginTime;
        this.use_url = use_url;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAccount() {
        return account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public String getRefreshToken() {
        return refreshToken;
    }

    public void setRefreshToken(String refreshToken) {
        this.refreshToken = refreshToken;
    }

    public Long getTotalSize() {
        return totalSize;
    }

    public void setTotalSize(Long totalSize) {
        this.totalSize = totalSize;
    }

    public Long getLeftSize() {
        return leftSize;
    }

    public void setLeftSize(Long leftSize) {
        this.leftSize = leftSize;
    }

    public Long getLoginTime() {
        return loginTime;
    }

    public void setLoginTime(Long loginTime) {
        this.loginTime = loginTime;
    }

    public String getUse_url() {
        return use_url;
    }

    public void setUse_url(String use_url) {
        this.use_url = use_url;
    }

}
