package com.grt.filemanager.orm.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SUGARSYNC_FILE".
 */
public class SugarsyncFile {

    private Long id;
    private String name;
    private String path;
    private Long size;
    private String mimeType;
    private Long lastModified;
    private Boolean isFolder;
    private Integer accountId;
    private String contentsUrl;
    private String refUrl;
    private String dataUrl;
    private Integer specialType;
    private Boolean isRFile;
    private String parentId;
    private String fileId;

    public SugarsyncFile() {
    }

    public SugarsyncFile(Long id) {
        this.id = id;
    }

    public SugarsyncFile(Long id, String name, String path, Long size, String mimeType, Long lastModified, Boolean isFolder, Integer accountId, String contentsUrl, String refUrl, String dataUrl, Integer specialType, Boolean isRFile, String parentId, String fileId) {
        this.id = id;
        this.name = name;
        this.path = path;
        this.size = size;
        this.mimeType = mimeType;
        this.lastModified = lastModified;
        this.isFolder = isFolder;
        this.accountId = accountId;
        this.contentsUrl = contentsUrl;
        this.refUrl = refUrl;
        this.dataUrl = dataUrl;
        this.specialType = specialType;
        this.isRFile = isRFile;
        this.parentId = parentId;
        this.fileId = fileId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public Long getSize() {
        return size;
    }

    public void setSize(Long size) {
        this.size = size;
    }

    public String getMimeType() {
        return mimeType;
    }

    public void setMimeType(String mimeType) {
        this.mimeType = mimeType;
    }

    public Long getLastModified() {
        return lastModified;
    }

    public void setLastModified(Long lastModified) {
        this.lastModified = lastModified;
    }

    public Boolean getIsFolder() {
        return isFolder;
    }

    public void setIsFolder(Boolean isFolder) {
        this.isFolder = isFolder;
    }

    public Integer getAccountId() {
        return accountId;
    }

    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    public String getContentsUrl() {
        return contentsUrl;
    }

    public void setContentsUrl(String contentsUrl) {
        this.contentsUrl = contentsUrl;
    }

    public String getRefUrl() {
        return refUrl;
    }

    public void setRefUrl(String refUrl) {
        this.refUrl = refUrl;
    }

    public String getDataUrl() {
        return dataUrl;
    }

    public void setDataUrl(String dataUrl) {
        this.dataUrl = dataUrl;
    }

    public Integer getSpecialType() {
        return specialType;
    }

    public void setSpecialType(Integer specialType) {
        this.specialType = specialType;
    }

    public Boolean getIsRFile() {
        return isRFile;
    }

    public void setIsRFile(Boolean isRFile) {
        this.isRFile = isRFile;
    }

    public String getParentId() {
        return parentId;
    }

    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    public String getFileId() {
        return fileId;
    }

    public void setFileId(String fileId) {
        this.fileId = fileId;
    }

}
