package com.grt.filemanager.orm.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SYNC_HISTORY".
 */
public class SyncHistory {

    private Long id;
    private Integer syncFlag;
    private Long historyFlag;
    private Long size;
    private Integer count;
    private Integer type;

    public SyncHistory() {
    }

    public SyncHistory(Long id) {
        this.id = id;
    }

    public SyncHistory(Long id, Integer syncFlag, Long historyFlag, Long size, Integer count, Integer type) {
        this.id = id;
        this.syncFlag = syncFlag;
        this.historyFlag = historyFlag;
        this.size = size;
        this.count = count;
        this.type = type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getSyncFlag() {
        return syncFlag;
    }

    public void setSyncFlag(Integer syncFlag) {
        this.syncFlag = syncFlag;
    }

    public Long getHistoryFlag() {
        return historyFlag;
    }

    public void setHistoryFlag(Long historyFlag) {
        this.historyFlag = historyFlag;
    }

    public Long getSize() {
        return size;
    }

    public void setSize(Long size) {
        this.size = size;
    }

    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

}
