package com.grt.filemanager.orm.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SYNC_SETTING".
 */
public class SyncSetting {

    private Long id;
    private Integer syncFlag;
    private String keyName;
    private String value;

    public SyncSetting() {
    }

    public SyncSetting(Long id) {
        this.id = id;
    }

    public SyncSetting(Long id, Integer syncFlag, String keyName, String value) {
        this.id = id;
        this.syncFlag = syncFlag;
        this.keyName = keyName;
        this.value = value;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getSyncFlag() {
        return syncFlag;
    }

    public void setSyncFlag(Integer syncFlag) {
        this.syncFlag = syncFlag;
    }

    public String getKeyName() {
        return keyName;
    }

    public void setKeyName(String keyName) {
        this.keyName = keyName;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

}
