package com.grt.filemanager.orm.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SYNC_INFO".
 */
public class SyncInfo {

    private Long id;
    private Integer syncFlag;
    private String insidePath;
    private Long size;
    private String checksum;
    private String version;
    private Boolean existed;
    private Boolean syncing;

    public SyncInfo() {
    }

    public SyncInfo(Long id) {
        this.id = id;
    }

    public SyncInfo(Long id, Integer syncFlag, String insidePath, Long size, String checksum, String version, Boolean existed, Boolean syncing) {
        this.id = id;
        this.syncFlag = syncFlag;
        this.insidePath = insidePath;
        this.size = size;
        this.checksum = checksum;
        this.version = version;
        this.existed = existed;
        this.syncing = syncing;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getSyncFlag() {
        return syncFlag;
    }

    public void setSyncFlag(Integer syncFlag) {
        this.syncFlag = syncFlag;
    }

    public String getInsidePath() {
        return insidePath;
    }

    public void setInsidePath(String insidePath) {
        this.insidePath = insidePath;
    }

    public Long getSize() {
        return size;
    }

    public void setSize(Long size) {
        this.size = size;
    }

    public String getChecksum() {
        return checksum;
    }

    public void setChecksum(String checksum) {
        this.checksum = checksum;
    }

    public String getVersion() {
        return version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    public Boolean getExisted() {
        return existed;
    }

    public void setExisted(Boolean existed) {
        this.existed = existed;
    }

    public Boolean getSyncing() {
        return syncing;
    }

    public void setSyncing(Boolean syncing) {
        this.syncing = syncing;
    }

}
