package com.grt.filemanager.orm.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "WEB_DAV_ACCOUNT".
 */
public class WebDavAccount {

    private Long id;
    private String protocol;
    private String hostname;
    private Integer port;
    private String account;
    private String password;
    private Boolean anonymous;
    private String token;
    private String refreshToken;
    private Long totalSize;
    private Long leftSize;
    private Long loginTime;

    public WebDavAccount() {
    }

    public WebDavAccount(Long id) {
        this.id = id;
    }

    public WebDavAccount(Long id, String protocol, String hostname, Integer port, String account, String password, Boolean anonymous, String token, String refreshToken, Long totalSize, Long leftSize, Long loginTime) {
        this.id = id;
        this.protocol = protocol;
        this.hostname = hostname;
        this.port = port;
        this.account = account;
        this.password = password;
        this.anonymous = anonymous;
        this.token = token;
        this.refreshToken = refreshToken;
        this.totalSize = totalSize;
        this.leftSize = leftSize;
        this.loginTime = loginTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getProtocol() {
        return protocol;
    }

    public void setProtocol(String protocol) {
        this.protocol = protocol;
    }

    public String getHostname() {
        return hostname;
    }

    public void setHostname(String hostname) {
        this.hostname = hostname;
    }

    public Integer getPort() {
        return port;
    }

    public void setPort(Integer port) {
        this.port = port;
    }

    public String getAccount() {
        return account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Boolean getAnonymous() {
        return anonymous;
    }

    public void setAnonymous(Boolean anonymous) {
        this.anonymous = anonymous;
    }

    public String getToken() {
        return token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public String getRefreshToken() {
        return refreshToken;
    }

    public void setRefreshToken(String refreshToken) {
        this.refreshToken = refreshToken;
    }

    public Long getTotalSize() {
        return totalSize;
    }

    public void setTotalSize(Long totalSize) {
        this.totalSize = totalSize;
    }

    public Long getLeftSize() {
        return leftSize;
    }

    public void setLeftSize(Long leftSize) {
        this.leftSize = leftSize;
    }

    public Long getLoginTime() {
        return loginTime;
    }

    public void setLoginTime(Long loginTime) {
        this.loginTime = loginTime;
    }

}
